set -g mouse off

set -q -g status-utf8 on                  # expect UTF-8 (tmux < 2.2)
setw -q -g utf8 on
set -sg repeat-time 500

set -g prefix2 C-a                        # GNU-Screen compatible prefix
bind C-a send-prefix -2

bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

bind X kill-window

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

#bind-key v run-shell 'tmux capture-pane -pS - > /tmp/tmux-pane.txt; tmux new-window "nvim -u ~/.vimrc /tmp/tmux-pane.txt"'

# edit configuration
bind e new-window -n "~/.tmux.conf" "EDITOR=\${EDITOR//mvim/vim} && EDITOR=\${EDITOR//gvim/vim} && \${EDITOR:-vim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"~/.tmux.conf sourced\""

set -g detach-on-destroy off
set -g history-limit 25000                 # boost history

set -g base-index 1           # start windows numbering at 1
setw -g pane-base-index 1     # make pane numbering consistent with windows

setw -g automatic-rename on   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed

set -g display-panes-time 100 # slightly longer pane indicators display time
set -g display-time 1000      # slightly longer status messages display time

set -g set-titles on          # set terminal title
set -g set-titles-string "#I:#W" #Set parent terminal title to reflect current window in tmux session 

set -g status-interval 10     # redraw status line every 10 seconds
set -g status-position bottom

#set -sg escape-time 0
set -sg repeat-time 300

setw -g aggressive-resize on

# clear both screen and history
bind -n C-l send-keys C-l \; run 'sleep 0.2' \; clear-history

# activity
set -g monitor-activity on
set -g visual-activity off

# -- navigation ----------------------------------------------------------------

bind Tab last-window        # move to last active window
# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right

# -- copy mode -----------------------------------------------------------------
#linux

if-shell 'test "$(uname)" = "Linux"' \
    "set -s copy-command 'xclip -selection clipboard -in'"

bind Enter copy-mode # enter copy mode
setw -g mode-keys vi
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection

#linux
if-shell 'test "$(uname)" = "Linux"' \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel'

if-shell 'test "$(uname)" = "Linux"' \
    'bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel'


#set -g lock-after-time 1000
#set -g lock-command "cmatrix -b -s -u 15 -C blue"
#set remain-on-exit off

# Session is considered to be remote when we ssh into host
if-shell 'test -n "$SSH_CLIENT"' \
    'source-file ~/.tmux.remote.conf'

bind -T root F12  \
    set prefix None \;\
    set key-table off \;\
    set status-style "fg=colour245,bg=colour238" \;\
    set window-status-current-format " #I:#W# " \;\
    set window-status-current-style "fg=colour232,bold,bg=colour254" \;\
    if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
    refresh-client -S \;\

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  set -u window-status-current-style \;\
  set -u window-status-current-format \;\
  refresh-client -S
